version: "2"
services:

  base:
    build: build
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  development:
    build: development
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  dev-trusty:
    build: trusty
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
